#!/bin/sh

lnxtotrmx(){
rsync -a --delete -e 'ssh -p 8022' ~/Documents ~/Music ~/Orgnote ~/Pictures ~/LearningArea u0_a119@192.168.43.1:~/storage/external-1/lnxhome/ && notify-send "Backup completed"
}

trmxtolnx(){
rsync -a --delete -e 'ssh -p 8022' u0_a119@192.168.43.1:~/storage/external-1/lnxhome/* ~/ && notify-send "Backup recovered"
}

case $1 in 
    lnxtotrmx) lnxtotrmx;;
    trmxtolnx) trmxtolnx;;
esac

