#!/bin/sh
# dependencies: grim slurp wayland clipboard(cli application)
color=$(grim -g "$(slurp -p -b 00000000)" - | convert - txt:- | awk 'END{print $3}')
if [ "$color" ]; then
$COPY "$color"
notify-send "Color copied to clipboard" "$color" --icon 'color-picker'
else
exit 0
fi
