#!/bin/sh 

if [ ! -d $HOME/Videos/screenrecords ]; then
   mkdir -p $HOME/Videos/screenrecords
fi

pid=`pgrep wf-recorder`
status=$?

if [ $status != 0 ] 
then 
 notify-send "Screenrecord has started"
 wf-recorder -g "$(slurp)" -f ~/Videos/screenrecords/sc-"$(date '+%d:%b:%y(%a)%I:%M:%S:%P')".mp4;
else 
  pkill --signal SIGINT wf-recorder
 notify-send "Screenrecord has stopped"
fi;
