#!/bin/sh

Directory=$(find "$HOME/.bin" -maxdepth 2 -type d \
    | $MENU -p 'Save:')
[ -z "$Directory" ] && exit 1

Name=$(printf '' | $MENU -p 'name:')
[ -z "$Name" ] && exit 1

Script="$Directory/$Name"
touch "$Script"
chmod +x "$Script"
ln -sf "$Script" "$LBIN"
printf '%s\n\n# ' '#!/bin/sh' > "$Script"

$TERMINAL -e $EDITOR "$Script"
