#!/bin/sh

file="${XDG_DATA_HOME}/todo/todo.txt"

if [ ! -d "${XDG_DATA_HOME}/todo" ]; then 
   mkdir -p "${XDG_DATA_HOME}/todo" && touch "$file"
fi

height=$(wc -l "$file" | awk '{print $1}')
prompt="Add/delete a task: "

cmd=$($MENU -l "$height" -p "$prompt" "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi

	cmd=$($MENU -l "$height" -p "$prompt" "$@" < "$file")
done

exit 0
