#!/bin/sh
# dependencies: grabc xorg clipboard(cli application)
color=$(grabc)
if [ "$color" ]; then
echo "$color" | $COPY 
notify-send "Color copied to clipboard" "$color" --icon 'color-picker'
else
exit 0
fi
